// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/palembang-digital/website/pkg/db"
	mock "github.com/stretchr/testify/mock"
)

// EventsService is an autogenerated mock type for the EventsService type
type EventsService struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, event
func (_m *EventsService) CreateEvent(ctx context.Context, event db.Event) (db.GetEventRow, error) {
	ret := _m.Called(ctx, event)

	var r0 db.GetEventRow
	if rf, ok := ret.Get(0).(func(context.Context, db.Event) db.GetEventRow); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(db.GetEventRow)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, db.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: ctx, id
func (_m *EventsService) DeleteEvent(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEvent provides a mock function with given fields: ctx, id
func (_m *EventsService) GetEvent(ctx context.Context, id int64) (db.GetEventRow, error) {
	ret := _m.Called(ctx, id)

	var r0 db.GetEventRow
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.GetEventRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetEventRow)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEvents provides a mock function with given fields: ctx
func (_m *EventsService) ListEvents(ctx context.Context) ([]db.ListEventsRow, error) {
	ret := _m.Called(ctx)

	var r0 []db.ListEventsRow
	if rf, ok := ret.Get(0).(func(context.Context) []db.ListEventsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListEventsRow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEvent provides a mock function with given fields: ctx, event
func (_m *EventsService) UpdateEvent(ctx context.Context, event db.Event) (db.GetEventRow, error) {
	ret := _m.Called(ctx, event)

	var r0 db.GetEventRow
	if rf, ok := ret.Get(0).(func(context.Context, db.Event) db.GetEventRow); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(db.GetEventRow)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, db.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
