ALTER TABLE events ALTER created_at
    TYPE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE events ALTER updated_at TYPE TIMESTAMP;

ALTER TABLE events ALTER scheduled_start
    TYPE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE events ALTER scheduled_end
    TYPE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
