ALTER TABLE IF EXISTS startups DROP COLUMN IF EXISTS slug;
ALTER TABLE IF EXISTS startups DROP COLUMN IF EXISTS one_liner;
ALTER TABLE IF EXISTS startups DROP COLUMN IF EXISTS description;
ALTER TABLE IF EXISTS startups DROP COLUMN IF EXISTS website;

DROP INDEX IF EXISTS idx_startups_slug;
