ALTER TABLE IF EXISTS events ALTER COLUMN updated_at SET NOT NULL
  , ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS organizations ALTER COLUMN updated_at SET NOT NULL
  , ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS startups ALTER COLUMN updated_at SET NOT NULL
  , ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS banners ALTER COLUMN updated_at SET NOT NULL
  , ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
