ALTER TABLE IF EXISTS events ALTER COLUMN updated_at DROP NOT NULL
  , ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE IF EXISTS organizations ALTER COLUMN updated_at DROP NOT NULL
  , ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE IF EXISTS startups ALTER COLUMN updated_at DROP NOT NULL
  , ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE IF EXISTS banners ALTER COLUMN updated_at DROP NOT NULL
  , ALTER COLUMN updated_at DROP DEFAULT;
