name: Continuous Integration
on: push
jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install UI dependencies
      run: make init-ui
    - name: Test UI
      run: make test-ui
    - name: Publish UI's test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./ui/coverage
        flags: ui
        name: ui-coverage

  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Test server
      run: make test-server
    - name: Publish server's test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: server
        name: server-coverage

  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set tag
      id: tags
      run: echo ::set-output name=tag::${GITHUB_SHA}
    - name: Login to hub.docker.com
      uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: palembangdigital
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build docker image
      run: docker build -t palembangdigital/website:${{ steps.tags.outputs.tag }} .
    - name: Push docker image
      run: docker push palembangdigital/website:${{ steps.tags.outputs.tag }}
