name: Continuous Integration
on: push
jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install UI dependencies
      run: make init-ui
    - name: Test UI
      run: make test-ui
    - name: Publish UI's test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./ui/coverage
        flags: ui
        name: ui-coverage

  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Test server
      run: make test-server
    - name: Publish server's test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: server
        name: server-coverage

  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:  
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        registry: ghcr.io
        tag_with_ref: true
        tag_with_sha: true

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://palembang-digital.herokuapp.com/
            https://palembang-digital.herokuapp.com/patal-team
            https://palembang-digital.herokuapp.com/admin/events
            https://palembang-digital.herokuapp.com/admin/events/create
          budgetPath: ./lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
