name: Continuous Integration
on: push
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Test server
        run: make test-server
      - name: Publish server's test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
          flags: server
          name: server-coverage

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://palembang-digital.fly.dev/
            https://palembang-digital.fly.dev/patal-team
            https://palembang-digital.fly.dev/admin/events
            https://palembang-digital.fly.dev/admin/events/create
          budgetPath: ./lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
